Repository Museum-Mate/musium-mate-data-crawling, pull requests merged in 2023-01, with the labels that each got.

#10 feat: Update crawling Notebook
  notebook/kjg/crawling-kjg.ipynb
Labels: Type: 🚀 Merge

#12 상세페이지에서 예매자 통계 부분 크롤링 노트북 리펙토링
  .gitignore
  data/README.md
  data/img/README.md
  notebook/kjg/crawling-kjg.ipynb
  requirements.txt
Labels: Type: 🚀 Merge

#13 9 상세 페이지 크롤링 메서드 리팩토링 및 통합
  notebook/lhj/crawling- detail-page.ipynb
  notebook/lhj/exhibition3.csv
  notebook/lhj/exhibition_230120_025900.csv
Labels: Status: 🐞 Bug, Status: 👀 In_Review, Type: 🔧 Refactor

#16 11 python 과 s3 버킷 연동 작업
  notebook/kjg/crawling-kjg.ipynb
  src/s3/s3_updownloader.py
Labels: Type: 🚀 Merge

#18 feat: s3에 데이터 올리는 기능 재추가
  src/s3/s3_updownloader.py
  src/s3/s3_uploaddir.py
Labels: Type: 🔧 Refactor, Type: 🚀 Merge

#15 무료 전시 데이터 구축
  .vscode/settings.json
  notebook/lhj/220120_crawling-not-paid-exhibitions.ipynb
  notebook/lhj/not-paid-exhibitions2_수정.numbers
Labels: Type: 🚀 Merge

#19 17 python을 이용해서 수집된 data를 db에 insert 하기
  notebook/crawling-charged.ipynb
  src/mysql/mysql_import_csv.py
Labels: Type: 🚀 Merge

#21 20 유료 무료 전시데이터 크롤링 노트북 병합
  notebook/crawling-charged.ipynb
  notebook/crawling-free-exhibition.ipynb
Labels: Type: 🚀 Merge
